prompts = [
    "Explain the concept of entropy in thermodynamics.",
    "Describe the process of photosynthesis in plants.",
    "Discuss the impact of artificial intelligence on job automation.",
    "Analyze the themes of love and betrayal in Shakespeare's 'Othello.'",
    "Compare and contrast socialism and capitalism as economic systems.",
    "Explain the greenhouse effect and its role in climate change.",
    "Discuss the history and significance of the Magna Carta.",
    "Explore the benefits and drawbacks of renewable energy sources.",
    "Analyze the role of mass media in shaping public opinion.",
    "Describe the process of DNA replication.",
    "Discuss the rise and fall of the Roman Empire.",
    "Explain the concept of supply and demand in economics.",
    "Explore the ethics of genetic engineering and cloning.",
    "Analyze the effects of globalization on cultural diversity.",
    "Discuss the impact of social media on mental health.",
    "Describe the process of mitosis and meiosis in cells.",
    "Discuss the benefits and drawbacks of nuclear energy.",
    "Explore the history and cultural significance of the Olympic Games.",
    "Explain the process of protein synthesis in cells.",
    "Discuss the history and impact of the Civil Rights Movement in the United States.",
    "Analyze the themes of power and corruption in George Orwell's '1984.'",
    "Describe the process of evolution by natural selection.",
    "Discuss the causes and consequences of World War I.",
    "Explore the role of women in ancient civilizations.",
    "Explain the concept of manifest destiny in American history.",
    "Discuss the history and impact of the Industrial Revolution.",
    "Analyze the rise and fall of the Byzantine Empire.",
    "Explore the history and cultural significance of the Renaissance.",
    "Discuss the impact of colonialism on indigenous cultures.",
    "Explain the process of continental drift and plate tectonics.",
    "Analyze the themes of justice and revenge in 'The Count of Monte Cristo' by Alexandre Dumas.",
    "Discuss the causes and consequences of the Great Depression.",
    "Explore the history and significance of the Silk Road.",
    "Explain the concept of cognitive dissonance in psychology.",
    "Discuss the impact of climate change on biodiversity.",
    "Analyze the role of religion in shaping historical events.",
    "Describe the process of cellular respiration.",
    "Discuss the benefits and drawbacks of genetically modified organisms (GMOs).",
    "Explore the history and impact of the Civil Rights Movement in South Africa.",
    "Explain the concept of natural selection and its role in evolution.",
    "Discuss the causes and consequences of the French Revolution.",
    "Analyze the themes of fate and free will in literature.",
    "Explore the history and cultural significance of ancient Egypt.",
    "Describe the process of fossilization.",
    "Discuss the impact of colonialism on economic development.",
    "Analyze the rise and fall of the Aztec Empire.",
    "Explore the history and cultural significance of the Samurai in Japan.",
    "Discuss the causes and consequences of the American Civil War.",
    "Explain the concept of cognitive development in children.",
    "Discuss the benefits and drawbacks of the European Union.",
    "Describe the process of weathering and erosion.",
    "Analyze the themes of identity and belonging in immigrant literature.",
    "Explore the history and impact of the Women's Suffrage Movement.",
    "Discuss the role of propaganda in shaping public opinion.",
    "Explain the concept of ecosystem dynamics.",
    "Discuss the impact of social class on access to education.",
    "Analyze the rise and fall of the Mongol Empire.",
    "Explore the history and cultural significance of the Maori people.",
    "Describe the process of speciation in biology.",
    "Discuss the benefits and drawbacks of universal healthcare.",
    "Explain the concept of cognitive biases in decision-making.",
    "Discuss the impact of technology on human relationships.",
    "Analyze the role of symbolism in literature.",
    "Explore the history and impact of the Harlem Renaissance.",
    "Describe the process of synaptic transmission in the nervous system.",
    "Discuss the causes and consequences of the Cold War.",
    "Explain the concept of cultural relativism in anthropology.",
    "Discuss the benefits and drawbacks of immigration.",
    "Analyze the rise and fall of the Ottoman Empire.",
    "Explore the history and cultural significance of the Aboriginal Australians.",
    "Describe the process of continental glaciation.",
    "Discuss the impact of income inequality on society.",
    "Explain the concept of operant conditioning in psychology.",
    "Discuss the benefits and drawbacks of cryptocurrency.",
    "Analyze the themes of war and peace in literature.",
    "Explore the history and impact of the Harlem Renaissance.",
    "Describe the process of neurotransmission in the brain.",
    "Discuss the causes and consequences of the Russian Revolution.",
    "Explain the concept of cultural appropriation.",
    "Discuss the benefits and drawbacks of democracy.",
    "Analyze the rise and fall of the British Empire.",
    "Explore the history and cultural significance of the Mayan civilization.",
    "Describe the process of plate tectonics.",
    "Discuss the impact of social media on political activism.",
    "Explain the concept of cognitive dissonance.",
    "Discuss the benefits and drawbacks of socialized medicine.",
    "Analyze the themes of power and corruption in literature.",
    "Explore the history and impact of the Black Death.",
    "Describe the process of synaptic transmission.",
    "Discuss the causes and consequences of the Vietnam War.",
    "Explain the concept of cultural diffusion.",
    "Discuss the benefits and drawbacks of globalization.",
    "Analyze the rise and fall of the Spanish Empire.",
    "Explore the history and cultural significance of the Vikings.",
    "Describe the process of continental drift.",
    "Discuss the impact of social media on body image.",
    "Explain the concept of classical conditioning.",
    "Discuss the benefits and drawbacks of renewable energy.",
    "Analyze the themes of love and tragedy in literature.",
    "Explore the history and impact of the Civil Rights Movement in India.",
        "What are the fundamental principles of quantum mechanics?",
    "Explain the concept of artificial intelligence and its applications.",
    "Discuss the impact of climate change on global ecosystems.",
    "Explore the history and significance of the Renaissance period.",
    "Analyze the factors contributing to income inequality in modern society.",
    "Describe the process of photosynthesis in plants.",
    "Discuss the role of neurotransmitters in human brain function.",
    "Investigate the ethical implications of genetic engineering.",
    "Compare and contrast different economic systems, such as capitalism and socialism.",
    "Explain the concept of entropy in thermodynamics.",
    "Discuss the psychological effects of social media on individuals.",
    "Explore the history and culture of ancient civilizations, such as the Maya or the Egyptians.",
    "Analyze the impact of globalization on cultural diversity.",
    "Describe the process of evolution by natural selection.",
    "Discuss the role of women in STEM fields throughout history.",
    "Investigate the effects of automation on the future of work.",
    "Compare and contrast different theories of personality, such as Freud's psychoanalytic theory and Maslow's hierarchy of needs.",
    "Explain the concept of sustainable development and its importance.",
    "Discuss the history and consequences of colonialism.",
    "Explore the science behind climate change and its potential solutions.",
    "Analyze the impact of social media on political discourse.",
    "Describe the process of DNA replication in cells.",
    "Discuss the ethical considerations of animal testing in scientific research.",
    "Investigate the history and philosophy of democracy.",
    "Compare and contrast different theories of ethics, such as utilitarianism and deontology.",
    "Explain the concept of biodiversity and its significance.",
    "Discuss the role of education in promoting social mobility.",
    "Explore the history and cultural significance of various forms of music, such as jazz or classical music.",
    "Analyze the effects of urbanization on the environment.",
    "Describe the process of cellular respiration in living organisms.",
    "Discuss the impact of artificial intelligence on job automation.",
    "Investigate the history and consequences of the Industrial Revolution.",
    "Compare and contrast different forms of government, such as democracy and dictatorship.",
    "Explain the concept of unconscious bias and its effects on decision-making.",
    "Discuss the role of religion in shaping societies throughout history.",
    "Explore the science behind renewable energy sources, such as solar and wind power.",
    "Analyze the effects of deforestation on biodiversity.",
    "Describe the process of mitosis and its significance in cell division.",
    "Discuss the ethical implications of human cloning.",
    "Investigate the history and philosophy of feminism.",
    "Compare and contrast different theories of motivation, such as Maslow's hierarchy of needs and Herzberg's two-factor theory.",
    "Explain the concept of cognitive dissonance and its effects on behavior.",
    "Discuss the impact of mass media on public opinion.",
    "Explore the history and cultural significance of various forms of literature, such as poetry or drama.",
    "Analyze the effects of pollution on public health.",
    "Describe the process of protein synthesis in cells.",
    "Discuss the ethical considerations of euthanasia.",
    "Investigate the history and consequences of slavery.",
    "Compare and contrast different theories of intelligence, such as Gardner's multiple intelligences theory and Spearman's g factor.",
    "Explain the concept of social stratification and its effects on society.",
    "Discuss the impact of globalization on the spread of infectious diseases.",
    "Explore the science behind genetic engineering and its applications in medicine.",
    "Analyze the effects of overfishing on marine ecosystems.",
    "Describe the process of meiosis and its role in sexual reproduction.",
    "Discuss the ethical implications of human enhancement technologies.",
    "Investigate the history and philosophy of pacifism.",
    "Compare and contrast different theories of leadership, such as trait theory and contingency theory.",
    "Explain the concept of confirmation bias and its effects on decision-making.",
    "Discuss the impact of immigration on host countries.",
    "Explore the history and cultural significance of various forms of visual art, such as painting or sculpture.",
    "Analyze the effects of climate change on food security.",
    "Describe the process of transcription and translation in gene expression.",
    "Discuss the ethical implications of capital punishment.",
    "Investigate the history and consequences of imperialism.",
    "Compare and contrast different theories of learning, such as behaviorism and constructivism.",
    "Explain the concept of groupthink and its effects on group decision-making.",
    "Discuss the impact of technology on human relationships.",
    "Explore the science behind the human microbiome and its effects on health.",
    "Analyze the effects of habitat destruction on endangered species.",
    "Describe the process of synaptic transmission in the nervous system.",
    "Discuss the ethical implications of artificial intelligence.",
    "Investigate the history and philosophy of existentialism.",
    "Compare and contrast different theories of emotion, such as the James-Lange theory and the Cannon-Bard theory.",
    "Explain the concept of cognitive development and its stages according to Piaget.",
    "Discuss the impact of cultural appropriation on marginalized communities.",
    "Explore the history and cultural significance of various forms of dance, such as ballet or hip-hop.",
    "Analyze the effects of water scarcity on agriculture.",
    "Describe the process of neurotransmission in the brain.",
    "Discuss the ethical considerations of privacy in the digital age.",
    "Investigate the history and consequences of the Cold War.",
    "Compare and contrast different theories of morality, such as relativism and absolutism.",
    "Explain the concept of bystander effect and its implications for social behavior.",
    "Discuss the impact of artificial intelligence on creativity.",
    "Explore the science behind the placebo effect and its implications for medicine.",
    "Analyze the effects of plastic pollution on marine life.",
    "Describe the process of memory formation and retrieval in the brain.",
    "Discuss the ethical implications of genetic testing.",
    "Investigate the history and philosophy of socialism.",
    "Compare and contrast different theories of addiction, such as the disease model and the social learning model.",
    "Explain the concept of social identity and its effects on intergroup relations.",
    "Discuss the impact of social media on mental health.",
    "Explore the history and cultural significance of various forms of theater, such as tragedy or comedy.",
    "Analyze the effects of income inequality on social mobility.",
    "Describe the process of evolution through natural selection.",
    "Discuss the ethical considerations of animal rights.",
    "Investigate the history and consequences of the Civil Rights Movement.",
    "Compare and contrast different theories of personality development, such as Freud's psychosexual theory and Erikson's psychosocial theory.",
    "Explain the concept of self-fulfilling prophecy and its effects on behavior.",
    "Discuss the impact of cyberbullying on adolescents.",
    "Explore the science behind the formation of stars and galaxies."
]
